name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set the value
        id: step_one
        run: |
            echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV - Encoding utf8 -Append
      - name: Use the value
        id: step_two
        run: |
            echo "${{ env.action_state }}" # This will output 'yellow'

